
#Server configuration settings
[server]
	#The time in ticks the server will wait when a dimension was queued to unload. This can be useful when rapidly loading and unloading dimensions, like e.g. throwing items through a nether portal a few time per second.
	#Range: > 0
	dimensionUnloadQueueDelay = 0
	#Base zombie summoning spawn chance. Allows changing the bonus zombie summoning mechanic.
	#Range: 0.0 ~ 1.0
	zombieBaseSummonChance = 0.1
	#Chance that a zombie (or subclass) is a baby. Allows changing the zombie spawning mechanic.
	#Range: 0.0 ~ 1.0
	zombieBabyChance = 0.05
	#Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
	removeErroringEntities = false
	#Set this to true to check the entire entity's collision bounding box for ladders instead of just the block they are in. Causes noticeable differences in mechanics so default is vanilla behavior. Default: false
	fullBoundingBoxLadders = false
	#Log cascading chunk generation issues during terrain population.
	logCascadingWorldGeneration = true
	#Vanilla will treat crafting recipess using empty tags as air, and allow you to craft with nothing in that slot. This changes empty tags to use BARRIER as the item. To prevent crafting with air.
	treatEmptyTagsAsAir = false
	#Controls the number threshold at which Packet51 is preferred over Packet52, default and minimum 64, maximum 1024
	#Range: 64 ~ 1024
	clumpingThreshold = 64
	#Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
	removeErroringTileEntities = false
	#Fix vanilla issues that cause worldgen cascading. This DOES change vanilla worldgen so DO NOT report bugs related to world differences if this flag is on.
	fixVanillaCascading = false

